name = input("Please enter your name: ")
age = int(input("Please enter your age: "))
height = float(input("Please enter your height in meters: "))
fav_number = int(input("Please enter your favourite number: "))
birth_year = 2025 - age  
print(name)
print(age)
print(height)
print(fav_number)
print(name,type(name),id(name))
print(age,type(age),id(age))
print(height,type(height),id(height))
print(fav_number,type(fav_number),id(fav_number))
print("your birth year is a approximetly :",birth_year,("based on your age of"),age)
